In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

In [3]:
df = pd.read_csv(r"C:\Users\M_dell\Downloads\Iris.csv")

In [4]:
df.head()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa


In [18]:
x = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = df['Species']

y=pd.factorize()[0]

TypeError: factorize() missing 1 required positional argument: 'values'

In [11]:
xt,xte,yt,yte = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [12]:
model = GaussianNB()
model.fit(xt,yt)

y_pred = model.predict(xte)

In [16]:
cm = confusion_matrix(yte,y_pred)
print(cm)


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [17]:
tn = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tp = cm[1][1]